version: 2

build:
  os: ubuntu-24.04
  apt_packages:
    - swig
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - python doc/rtd_build.py

python:
  install:
    - requirements: doc/requirements.txt

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false
